spawn:
  world: world
  join: true
  death: true
join:
  alert: true
  message: "&8[&cSERVER&8]&6 %player%&7 joined!"
leave:
  alert: true
  message: "&8[&cSERVER&8]&6 %player%&7 disconnected!"
color:
  bracket: "&8"
  name: "&c"
  text: "&7"
  highlight: "&6"
lunar:
  kick: false
  message: "&8[&cSERVER&8]&7 This is lunar only server!"
msg:
  sender: "&8[&cMSG&8]&7 To&6 %receiver%&8 >&7 %msg%"
  receiver: "&8[&cMSG&8]&7 From&6 %sender%&8 >&7 %msg%"
commands:
  crash: true
  crawl: true
  skick: true
  sit: true
  troll: true
  pinfo: true
  rp: true
  lunar: true
  cmdblock: true
  vanish: true
  msg: true
  gmc: true
  gms: true
  gma: true
  gmsp: true
  spawn: true
  fly: true
  wc: true
  ic: true
commandblock:
  message: "&8[&cSERVER&8]&7 You're not allowed to do this!"
